import type { Issue } from '@/lib/types';

export const issues: Issue[] = [
  {
    id: 'T-1',
    title: 'Leaky faucet in the main kitchen',
    description: 'The faucet in the main kitchen sink has been dripping constantly for the past two days. It needs to be repaired to conserve water.',
    category: 'Facility',
    subCategory: 'Internal',
    status: 'Pending',
    assignedTo: 'Operations Manager',
    createdAt: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: 'T-2',
    title: 'Cannot connect to the office Wi-Fi',
    description: 'My laptop is unable to connect to the "Office-Guest" Wi-Fi network. I have tried restarting my device and the router.',
    category: 'IT',
    subCategory: 'Internet',
    status: 'Accepted',
    assignedTo: 'IT Manager',
    createdAt: new Date('2024-07-21T09:30:00Z'),
  },
  {
    id: 'T-3',
    title: 'Request for new ergonomic chairs',
    description: 'The design team requires 5 new ergonomic chairs to replace the old ones, which are causing back pain.',
    category: 'Purchase',
    status: 'Ongoing',
    assignedTo: 'Purchaser',
    createdAt: new Date('2024-07-19T14:00:00Z'),
  },
  {
    id: 'T-4',
    title: 'Photocopier is jamming paper',
    description: 'The main photocopier on the 2nd floor keeps jamming paper. We have tried clearing it, but the problem persists.',
    category: 'IT',
    subCategory: 'Office Machines',
    status: 'Finished',
    assignedTo: 'IT Manager',
    createdAt: new Date('2024-07-18T11:00:00Z'),
  },
  {
    id: 'T-5',
    title: 'Broken window in the conference room',
    description: 'A window in Conference Room 3 was found cracked this morning. It needs immediate replacement for security reasons.',
    category: 'Facility',
    subCategory: 'External',
    status: 'Ongoing',
    assignedTo: 'Operations Manager',
    createdAt: new Date('2024-07-21T08:00:00Z'),
  },
  {
    id: 'T-6',
    title: 'Software license renewal for Adobe CC',
    description: 'The Adobe Creative Cloud licenses for the marketing team are expiring next week. We need to renew them.',
    category: 'IT',
    subCategory: 'Software',
    status: 'Pending',
    assignedTo: 'IT Manager',
    createdAt: new Date('2024-07-22T15:00:00Z'),
  },
];
